name: build app

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: build gradle project
        run: ./gradlew build

      - name: build apk 
        run: ./gradlew assembleDebug

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/release/
