name: build and release signed apk

on:
  workflow_dispatch:

jobs:
  build-and-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: make properties
        run: |
          touch keystore.properties
          touch placeholder
          echo "keyAlias=placeholder" >> keystore.properties
          echo "keyPassword=placeholder" >> keystore.properties
          echo "storeFile=placeholder" >> keystore.properties
          echo "storePassword=placeholder" >> keystore.properties

      - name: build gradle project
        run: ./gradlew build

      - name: build apk 
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      
      - name: Set current date as env variable
        run: |
          date_today=$(date +'%Y-%m-%d_%H-%M')
          echo "date_today=$date_today" >> $GITHUB_ENV
          mkdir releases
          apk_path="./releases/FQHLL_Keyboard_$date_today.apk"
          echo "apk_path=$apk_path" >> $GITHUB_ENV

      - name: copy debug apk
        run: |
          cp ${{steps.sign_app.outputs.signedReleaseFile}} "$apk_path"

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: apk zip file
          path: ${{ env.apk_path }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          preserve_order: true
          fail_on_unmatched_files: true
          tag_name: ${{ env.date_today }}
          name: Prerelease (generated by github actions) ${{ env.date_today }}
          append_body: true
          body: |
            This project is released under the MIT license. You can obtain a copy of the license [here](https://github.com/shun4midx/FQ-HLL-Keyboard/blob/main/LICENSE).
          files: |
            ${{ env.apk_path }}
            LICENSE
